export const tagLabels: Record<string, string> = {
    battle_rap: "Баттл-рэп",
    movie: "Фильм",
    game: "Игра",
    series: "Сериал",
    degrod: "Дегрод",
    videos: "Видео",
    kbk: "Кубок МЦ",
    kbk_reborn: "Кубок МЦ: Reborn",
    kbk_summer_trip: "Кубок МЦ: Summer Trip",
    kbk_new_era: "Кубок МЦ: New Era",
    kbk_generation: "Кубок МЦ: Generation",
    kbk_backyard: "Кубок МЦ: Backyard",
    kbk_da_shift: "Кубок МЦ: Da Shift",
    kbk_7: "Кубок МЦ: 7",
    kbk_infinity: "Кубок МЦ: Infinity",
    kbk_chains: "Кубок МЦ: Chains",
    kbk_x: "Кубок МЦ: X",
    kbk_11: "Кубок МЦ: 11",
    kbk_ny: "Кубок МЦ: New Year",
    kbk_13: "Кубок МЦ: XIII",
    kbk_legacy_1: "Кубок МЦ: Legacy pt. 1",
    kbk_legacy_2: "Кубок МЦ: Legacy pt. 2",
    kbk_karma: "Кубок МЦ: KARMA",
    kbk_march: "Кубок МЦ: MARCH",
    kbk_slovo: "Кубок МЦ: SLOVO",
    kbk_ultimate: "Кубок МЦ: Ultimate",
    kbk_ultimate_2: "Кубок МЦ: Ultimate 2",
    kbk_off_season: "Кубок МЦ: Off Season",
    kbk_ultimate_final: "Кубок МЦ: Ultimate 3",
    kbk_xx: "Кубок МЦ: XX",
    kbk_summer_trap: "Кубок МЦ: Summer Trap",
    kbk_xx_2: "Кубок МЦ: XX 2",
    kbk_xx_3: "Кубок МЦ: XX 3",
    kbk_back_to_basics: "Кубок МЦ: Back to basics",
    kbk_solo_champ: "Кубок МЦ: Соло Турнир",
    kbk_2_2: "Кубок МЦ: Турнир 2х2",
    kbk_survival: "Кубок МЦ: Survival",
    retro: "Ретроспектива",
    anime: "Аниме",
    slovo: "SLOVO",
    rbl: "RBL",
    rbl_season_1: "RBL: 1 сезон",
    rbl_off_season_1: "RBL: Межсезонье 1",
    rbl_season_2: "RBL: 2 сезон",
    rbl_off_season_2: "RBL: Межсезонье 2",
    rbl_season_3: "RBL: 3 сезон",
    rbl_all_stars: "RBL: All Starts",
    rbl_universe: "RBL: Universe",
    rbl_off_season_3: "RBL: Межсезонье 3",
    rbl_league_1: "RBL: League 1",
    rbl_chance: "RBL: Chance",
    sverh: "Сверхъестественное",
    coop: "Кооператив",
    music: "Музыка",
    unknown: "Неизвестно",
    140: "140 BPM",
    rnb: "Рвать на битах",
    bv16: "Беременна в 16",
    versus: "Версус",
    wed: "4 Свадьбы",
    requested: "Заказы",
    creator_alco: "Алкостримы",
    creator_battle_review: "Просмотр своих баттлов",
    creator_best: "Хайлайты",
    creator_call: "Созвоны",
    creator_content: "Авторский контент",
    creator_judging: "Судейства",
    creator_release: "Заявки, треки",
    creator_special: "Особые стримы",
    master_of_games: "Мастер игорей",
    pens: "Пенсионеры",
    strela: "STRELASPB",
    fb: "Fresh Blood",
    naruto: "Наруто",
    got: "Игра престолов",
    chsv: "ЧСВ",
    drago: "Драго",
    pacanki: "Пацанки",
    br_main: "Баттл-рэп Главное",
    triplet: "Триплет",
    tlou: "Одни из нас",
    exile: "Эксайл",
    bcb: "БЧБ",
    bb: "Во все тяжкие",
    fifa: "FIFA",
    probattle: "ProBattle",
    razved: "Немножко разведены",
    demon_souls: "Demon's Souls",
    auction: "Аукцион",
    twd: "Ходячие мертвецы",
    saw: "Пила",
    zlovo: "Zlovo",
    quiz: "Тест",
    jojo: "ДжоДжо",
    polozh: "Положняк",
    milf: "Особняк милф",
    m_zh: "Мужское/Женское",
    daredevil: "Сорвиголова",
    cs: "Counter Strike",
    best: "Хайлайты",
    re7: "Resident Evil 7",
    lotr: "Властелин колец",
    irl: "ИРЛ",
    tbi: "The Beast Inside",
    hp: "Гарри Поттер",
    dark_souls: "Dark Souls",
    sg: "Игра в кальмара",
    jujutsu: "Магическая битва",
    dima: "Дима Хулиган",
    kcd: "Kingdom Come: Deliverance",
    ji: "дядя JI",
    hearts: "Сердца за любовь",
    gta: "GTA",
    gr_falls: "Гравити Фолз",
    tier_list: "Тир-лист",
    tanakaboss: "Tanakaboss",
    sw: "Звездные войны",
    re8: "Resident Evil 8",
    re2: "Resident Evil 2",
    outlast: "Outlast",
    lynch: "Lynch Battle",
    kaguya: "Госпожа Кагуя",
    hunt: "Hunt: Showdown",
    haikyu: "Волейбол!",
    gow: "God of War",
    baki: "Боец Баки",
    thohh: "Призрак дома на холме",
    summer: "Бесконечное лето",
    outlast2: "Outlast 2",
    mafia: "Mafia",
    geass: "Код Гиас",
    fullmetal: "Стальной алхимик",
    demon_slayer: "Клинок, рассекающий демонов",
    au: "Among Us",
    arcane: "Аркейн",
    aang: "Аватар: Легенда об Аанге",
    witcher: "Ведьмак",
    pl: "Поляк",
    minecraft: "Майнкрафт",
    mafia2: "Mafia 2",
    half_sword: "Half Sword",
    dbh: "Detroit: Become Human",
    aimeet: "Нейросозвон",
    "24h": "24 Часа",
    vpiska: "Вписка",
    ud: "Until Dawn",
    subnautica: "Subnautica",
    re4: "Resident Evil 4",
    opm: "Ванпанчмен",
    mashle: "Магия и мускулы",
    mafia_oc: "Mafia: Old Country",
    link_click: "Агент времени",
    konosuba: "Коносуба",
    kcd2: "Kingdom Come: Deliverance 2",
    hod: "Дом Дракона",
    fargo: "Фарго",
    er: "Elden Ring",
    dirk_gently: "Дирк Джентли",
    death_note: "Тетрадь смерти",
    comedy_table: "Comedy Table",
    chainsaw_man: "Человек-бензопила",
    bully: "Bully",
    bibop: "Бибоп",
    alice: "Алиса в пограничье",
    tog: "Башня Бога",
    st: "ОСД",
    spy_family: "Семья шпиона",
    skyrim: "Skyrim",
    queen: "Ход Королевы",
    phasmophobia: "Phasmophobia",
    lof: "Layers of Fear",
    hogwarts: "Hogwarts Legacy",
    gurren: "Гуррен-Лаганн",
    fof: "Fears to Fathom",
    dispatch: "Dispatch",
    dan: "Дандандан",
    bmw: "Black Myth: Wukong",
    bd: "ДР Стрим",
    awo: "A Way Out",
    aot: "Атака титанов",
    wwe: "WWE 2k26",
    wus: "The Wolf Among Us",
    vedau: "Д/ф Ведаю",
    usher: "Падение дома Ашеров",
    tpn: "Обещанный Неверленд",
    tlasosb: "The Life and Suffering of Sir Brante",
    tinny_bunny: "Tinny Bunny",
    the_boys: "Пацаны",
    rer: "Resident Evil Requiem",
    re3: "Resident Evil 3",
    prison_school: "Школа-тюрьма",
    nfs_carbon: "Need for Speed: Carbon",
    mvin: "Место встречи изменить нельзя",
    milodrama: "Мылодрама",
    man_of_medan: "Man of Medan",
    mafia_lh: "Mafia: Lost Heaven",
    little_hope: "Little Hope",
    ldr: "Любовь. Смерть. Роботы",
    lac: "Законопослушный гражданин",
    inzoi: "inZOI",
    hla: "Half-Life: Alyx",
    hbm: "Hitman: Blood Money",
    gbd: "Необъятный Океан",
    colombo: "Коломбо",
    col: "Call of LDPR",
    clgw: "Crime Life: Gang Wars",
    champloo: "Самурай Чамплу",
    basilisk: "Василиск",
    b_lagoon: "Пираты Черной Лагуны",
    anoes: "Кошмар на улице Вязов",
    "17mgnov": "17 мгновений весны",
    "007": "007 First Light",
    tms: "Toilet Management Simulator",
    minesweeper: "Сапёр",
    ninh: "No, I’m Not a Human",
    baby_steps: "Baby Steps",
    petka: "Петька и Василий Иванович спасают галактику",
    hoa: "House of Ashes",
    hitman2: "Hitman 2: Silent Assassin",
    dale: "Dale & Dawson Stationery Supplies",
    indika: "INDIKA",
    madagaskar: "Мадагаскар",
    lethal: "Lethal Company",
    dread: "Dread Hunger",
    goiwbf: "Getting Over It with Bennett Foddy",
    only_up: "Only Up",
    itt: "It Takes Two",
    w3: "Warcraft 3",
    dbd: "Dead by Daylight",
    traffic: "Трафикк",
    saw2: "Пила 2",
    saw5: "Пила 5",
    saw3: "Пила 3",
    saw4: "Пила 4",
    f1: "F1",
    geju: "Я слежу за тобой",
    eduard: "Эдуард Суровый. Слёзы Брайтона",
    shum: "Шум",
    sherlok_gs: "Шерлок Холмс: Игра теней",
    sherlok: "Шерлок Холмс",
    shapito: "Шапито-шоу: Любовь и дружба",
    chudo: "Чудо в камере №7",
    jigokuraku: "Райский ад",
    zom100: "Предсмертный список зомби",
    helldivers: "Helldivers 2",
    cooking: "Кукинг",
    silicon: "Силиконовая долина",
    saw6: "Пила 6",
    hobbit: "Хоббит",
    gustav: "Густав",
};

export function getTagLabel(tag: string): string {
  return tagLabels[tag] ?? tag;
}

export function isVisibleContentTag(tag: string): boolean {
  return tag.startsWith("kbk_") || tag.startsWith("rbl_");
}
