export const tagLabels: Record<string, string> = {
    battle_rap: "Баттл-рэп",
    movie: "Фильм",
    game: "Игра",
    series: "Сериал",
    degrod: "Дегрод",
    videos: "Видео",
    kbk: "Кубок МЦ",
    retro: "Ретроспектива",
    anime: "Аниме",
    slovo: "SLOVO",
    rbl: "RBL",
    sverh: "Сверхъестественное",
    coop: "Кооператив",
    music: "Музыка",
    unknown: "Неизвестно",
    140: "140 BPM",
    rnb: "Рвать на битах",
    bv16: "Беременна в 16",
    versus: "Версус",
    wed: "4 Свадьбы",
    requested: "Заказы",
    pens: "Пенсионеры",
    strela: "STRELASPB",
    fb: "Fresh Blood",
    naruto: "Наруто",
    got: "Игра престолов",
    chsv: "ЧСВ",
    drago: "Драго",
    pacanki: "Пацанки",
    br_main: "Баттл-рэп Главное",
    triplet: "Триплет",
    tlou: "Одни из нас",
    exile: "Эксайл",
    bcb: "БЧБ",
    bb: "Во все тяжкие",
    fifa: "FIFA",
    probattle: "ProBattle",
    razved: "Немножко разведены",
    demon_souls: "Demon's Souls",
    auction: "Аукцион",
    twd: "Ходячие мертвецы",
    saw: "Пила",
    zlovo: "Zlovo",
    quiz: "Тест",
    jojo: "ДжоДжо",
    polozh: "Положняк",
    milf: "Особняк милф",
    m_zh: "Мужское/Женское",
    daredevil: "Сорвиголова",
    cs: "Counter Strike",
    best: "Хайлайты",
    re7: "Resident Evil 7",
    lotr: "Властелин колец",
    irl: "ИРЛ",
    tbi: "The Beast Inside",
    hp: "Гарри Поттер",
    dark_souls: "Dark Souls",
    sg: "Игра в кальмара",
    jujutsu: "Магическая битва",
    dima: "Дима Хулиган",
    kcd: "Kingdom Come: Deliverance",
    ji: "дядя JI",
    hearts: "Сердца за любовь",
    gta: "GTA",
    gr_falls: "Гравити Фолз",
    tier_list: "Тир-лист",
    tanakaboss: "Tanakaboss",
    sw: "Звездные войны",
    re8: "Resident Evil 8",
    re2: "Resident Evil 2",
    outlast: "Outlast",
    lynch: "Lynch Battle",
    kaguya: "Госпожа Кагуя",
    hunt: "Hunt: Showdown",
    haikyu: "Волейбол!",
    gow: "God of War",
    baki: "Боец Баки",
    thohh: "Призрак дома на холме",
    summer: "Бесконечное лето",
    outlast2: "Outlast 2",
    mafia: "Mafia",
    geass: "Код Гиас",
    fullmetal: "Стальной алхимик",
    demon_slayer: "Клинок, рассекающий демонов",
    au: "Among Us",
    arcane: "Аркейн",
    aang: "Аватар: Легенда об Аанге",
    witcher: "Ведьмак",
    pl: "Поляк",
    minecraft: "Майнкрафт",
    mafia2: "Mafia 2",
    half_sword: "Half Sword",
    dbh: "Detroit: Become Human",
    aimeet: "Нейросозвон",
    "24h": "24 Часа",
    vpiska: "Вписка",
    ud: "Until Dawn",
    subnautica: "Subnautica",
    re4: "Resident Evil 4",
    opm: "Ванпанчмен",
    mashle: "Магия и мускулы",
    mafia_oc: "Mafia: Old Country",
    link_click: "Агент времени",
    konosuba: "Коносуба",
    kcd2: "Kingdom Come: Deliverance 2",
    hod: "Дом Дракона",
    fargo: "Фарго",
    er: "Elden Ring",
    dirk_gently: "Дирк Джентли",
    death_note: "Тетрадь смерти",
    comedy_table: "Comedy Table",
    chainsaw_man: "Человек-бензопила",
    bully: "Bully",
    bibop: "Бибоп",
    alice: "Алиса в пограничье",
    tog: "Башня Бога",
    st: "ОСД",
    spy_family: "Семья шпиона",
    skyrim: "Skyrim",
    queen: "Ход Королевы",
    phasmophobia: "Phasmophobia",
    lof: "Layers of Fear",
    hogwarts: "Hogwarts Legacy",
    gurren: "Гуррен-Лаганн",
    fof: "Fears to Fathom",
    dispatch: "Dispatch",
    dan: "Дандандан",
    bmw: "Black Myth: Wukong",
    bd: "ДР Стрим",
    awo: "A Way Out",
    aot: "Атака титанов",
    wwe: "WWE 2k26",
    wus: "The Wolf Among Us",
    vedau: "Д/ф Ведаю",
    usher: "Падение дома Ашеров",
    tpn: "Обещанный Неверленд",
    tlasosb: "The Life and Suffering of Sir Brante",
    tinny_bunny: "Tinny Bunny",
    the_boys: "Пацаны",
    rer: "Resident Evil Requiem",
    re3: "Resident Evil 3",
    prison_school: "Школа-тюрьма",
    nfs_carbon: "Need for Speed: Carbon",
    mvin: "Место встречи изменить нельзя",
    milodrama: "Мылодрама",
    man_of_medan: "Man of Medan",
    mafia_lh: "Mafia: Lost Heaven",
    little_hope: "Little Hope",
    ldr: "Любовь. Смерть. Роботы",
    lac: "Законопослушный гражданин",
    inzoi: "inZOI",
    hla: "Half-Life: Alyx",
    hbm: "Hitman: Blood Money",
    gbd: "Необъятный Океан",
    colombo: "Коломбо",
    col: "Call of LDPR",
    clgw: "Crime Life: Gang Wars",
    champloo: "Самурай Чамплу",
    basilisk: "Василиск",
    b_lagoon: "Пираты Черной Лагуны",
    anoes: "Кошмар на улице Вязов",
    "17mgnov": "17 мгновений весны",
    "007": "007 First Light",
    tms: "Toilet Management Simulator",
    minesweeper: "Сапёр",
    ninh: "No, I’m Not a Human",
    baby_steps: "Baby Steps",
    petka: "Петька и Василий Иванович спасают галактику",
    hoa: "House of Ashes",
    hitman2: "Hitman 2: Silent Assassin",
    dale: "Dale & Dawson Stationery Supplies",
    indika: "INDIKA",
    madagaskar: "Мадагаскар",
    lethal: "Lethal Company",
    dread: "Dread Hunger",
    goiwbf: "Getting Over It with Bennett Foddy",
    only_up: "Only Up",
    itt: "It Takes Two",
    w3: "Warcraft 3",
    dbd: "Dead by Daylight",
    traffic: "Трафикк",
    saw2: "Пила 2",
    saw5: "Пила 5",
    saw3: "Пила 3",
    saw4: "Пила 4",
    f1: "F1",
    geju: "Я слежу за тобой",
    eduard: "Эдуард Суровый. Слёзы Брайтона",
    shum: "Шум",
    sherlok_gs: "Шерлок Холмс: Игра теней",
    sherlok: "Шерлок Холмс",
    shapito: "Шапито-шоу: Любовь и дружба",
    chudo: "Чудо в камере №7",
    jigokuraku: "Райский ад",
    zom100: "Предсмертный список зомби",
    helldivers: "Helldivers 2",
    cooking: "Кукинг",
    silicon: "Силиконовая долина",
    saw6: "Пила 6",
    hobbit: "Хоббит",
    gustav: "Густав",
};

export function getTagLabel(tag: string): string {
  return tagLabels[tag] ?? tag;
}